// Professional skills from the existing resume, career chapters and toolkit.
// Keep fictional project concepts out of this inventory.
export const technicalToolkit = [
  {
    title: 'Cloud & Kubernetes',
    description:
      'Cloud architecture, Kubernetes operations, environment provisioning and event-driven autoscaling.',
    items: [
      'Amazon Web Services (AWS)',
      'Google Cloud Platform (GCP)',
      'Amazon EKS',
      'Amazon EC2',
      'Kubernetes',
      'Helm',
      'Docker',
      'Istio',
      'Ambassador',
      'AWS Auto Scaling',
      'Load balancing',
      'KEDA',
      'Linux',
    ],
    href: '#platform-engineering',
    linkLabel: 'Kubernetes at PicPay',
  },
  {
    title: 'Infrastructure as code & delivery',
    description:
      'Repeatable infrastructure, automated delivery pipelines and GitOps workflows for engineering teams.',
    items: [
      'Infrastructure as Code (IaC)',
      'Terraform',
      'Terragrunt',
      'Atlantis',
      'Argo CD (ArgoCD)',
      'GitOps',
      'GitLab CI/CD',
      'Jenkins',
      'Ansible',
      'Chef',
      'Gradle',
      'Nexus',
    ],
    href: '#experience',
    linkLabel: 'Cloud migration & delivery work',
  },
  {
    title: 'Observability & reliability',
    description:
      'Monitoring, dashboards and tracing that support incident response, service objectives and recovery planning.',
    items: [
      'Datadog',
      'Prometheus',
      'Grafana',
      'New Relic',
      'Elasticsearch',
      'Logz.io',
      'Kibana',
      'Zabbix',
      'Application performance monitoring (APM)',
      'Distributed tracing',
      'Service-level objectives (SLOs)',
      'Incident response',
      'Disaster recovery',
      'Multi-region recovery',
      'On-call operations',
      'Postmortem analysis',
      'Recovery time objectives (RTO)',
      'Recovery point objectives (RPO)',
    ],
    href: '#observability',
    linkLabel: 'Observability at iFood',
  },
  {
    title: 'Security & infrastructure services',
    description:
      'Infrastructure services and security checks integrated into the software delivery process.',
    items: [
      'HashiCorp Vault',
      'HashiCorp Consul',
      'DevSecOps',
      'AWS / GCP cloud security',
      'Identity and Access Management (IAM)',
      'Amazon VPC',
      'Amazon Route 53',
      'AWS Transit Gateway',
      'Network segmentation',
      'Static application security testing (SAST)',
      'Dynamic application security testing (DAST)',
    ],
    href: '#experience',
    linkLabel: 'Security in delivery pipelines',
  },
  {
    title: 'Programming & integrations',
    description:
      'Infrastructure tooling, service integrations, messaging and durable streaming for production workflows.',
    items: [
      'Go (Golang)',
      'Python',
      'TypeScript',
      'Groovy',
      'Shell scripting',
      'REST APIs',
      'gRPC',
      'RabbitMQ',
      'Apache Kafka',
      'Redis',
      'Amazon SQS',
      'Server-Sent Events (SSE)',
    ],
    href: '#ai-infrastructure',
    linkLabel: 'Engineering the agent workflow',
  },
  {
    title: 'AI engineering & LLMOps',
    description:
      'Production AI agents with model routing, human approvals, durable execution and an inspectable audit trail.',
    items: [
      'LangChain',
      'LangGraph',
      'Amazon Bedrock',
      'Vertex AI',
      'Model Context Protocol (MCP)',
      'Human-in-the-loop workflows',
      'LLMOps',
      'MLOps',
      'AIOps',
      'Anthropic Claude',
      'Anthropic API',
      'Retrieval-augmented generation (RAG)',
      'Tool / function calling',
      'Prompt engineering',
      'Model routing',
      'Prompt caching',
      'Execution audit trails',
    ],
    href: '#ai-infrastructure',
    linkLabel: 'Production AI at Alloy / Kinter',
  },
];
